### ISSUE TITLE
Exception when issuing Ctrl-C 

### ISSUE THREAD

**Issue by gsleap** [MWATelescope/manta-ray-client#6]
This is mostly just a case of catching an exception, to make it look abort gracefully:
(mana-ray)gsleap@mwa-process02:~/mantaray$ mwa_client -c test.csv
Submitted job: 2622
Processing: Job id: 2622 type: 0 params: {'freqres': '40', 'flags': ['-flagdcchannels', '-allowmissing'], 'timeres': '2', 'edgewidth': '80', 'obs_id': '1122202536', 'conversion': 'ms'}
```
^C
Traceback (most recent call last):
  File "/home/gsleap/mantaray/env/bin/mwa_client", line 11, in <module>
    load_entry_point('mantaray-client==0.1.0', 'console_scripts', 'mwa_client')()
  File "/home/gsleap/mantaray/env/lib/python3.4/site-packages/mantaray_client-0.1.0-py3.4.egg/mantaray/scripts/mwa_client.py", line 318, in main
  File "/usr/lib/python3.4/queue.py", line 176, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.4/threading.py", line 294, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
(mana-ray)gsleap@mwa-process02:~/mantaray$
```

**Comment by davepallot** [comment]
Just have to catch the KeyboardInterrupt.

**Comment by davepallot** [comment]
commit: b867a8c7ff79a7ae0f0d02db55377139097ce44e
